# Generated by Django 5.1.4 on 2025-03-20 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='casetbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('incident_place', models.CharField(max_length=100)),
                ('incident_pin', models.BigIntegerField()),
                ('incident_post', models.CharField(max_length=100)),
                ('incident_district', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='courttbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='forensicstafftbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('regno', models.BigIntegerField()),
                ('forensicplace', models.CharField(max_length=100)),
                ('forensicpin', models.CharField(max_length=100)),
                ('forensicpost', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='logintbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='case_alloctbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('CASEID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.casetbl')),
                ('STAFFID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.forensicstafftbl')),
            ],
        ),
        migrations.CreateModel(
            name='forensic_evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('descripition', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('ALLOCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.case_alloctbl')),
            ],
        ),
        migrations.AddField(
            model_name='forensicstafftbl',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.logintbl'),
        ),
        migrations.CreateModel(
            name='evidence_requesttbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('CASEID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.casetbl')),
                ('COURT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forensic_app.courttbl')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.logintbl')),
            ],
        ),
        migrations.AddField(
            model_name='courttbl',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.logintbl'),
        ),
        migrations.CreateModel(
            name='chattbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('FROM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='forensic_app.logintbl')),
                ('TO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='forensic_app.logintbl')),
            ],
        ),
        migrations.CreateModel(
            name='police_stationtbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.logintbl')),
            ],
        ),
        migrations.CreateModel(
            name='evidencetbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencename', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('descripition', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('CASEID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.casetbl')),
                ('POLICE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.police_stationtbl')),
            ],
        ),
        migrations.AddField(
            model_name='casetbl',
            name='POLICE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forensic_app.police_stationtbl'),
        ),
        migrations.CreateModel(
            name='anony_casetbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('incident_place', models.CharField(max_length=100)),
                ('incident_pin', models.BigIntegerField()),
                ('incident_post', models.CharField(max_length=100)),
                ('incident_district', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('POLICE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forensic_app.police_stationtbl')),
            ],
        ),
        migrations.CreateModel(
            name='userlocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.logintbl')),
            ],
        ),
        migrations.CreateModel(
            name='usertbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('place', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('post', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.logintbl')),
            ],
        ),
        migrations.CreateModel(
            name='feedbacktbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.FloatField()),
                ('feedback', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.usertbl')),
            ],
        ),
        migrations.AddField(
            model_name='casetbl',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forensic_app.usertbl'),
        ),
    ]
