# Generated by Django 5.1.4 on 2025-04-04 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='firtbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir', models.FileField(upload_to='')),
                ('CASEID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forensic_app.casetbl')),
            ],
        ),
    ]
