# Generated by Django 5.1.4 on 2025-04-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic_app', '0002_firtbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicstafftbl',
            name='district',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
